name: Workflow_Test


on: [pull_request, push]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      python-version: ['3.6','3.9']
    steps: 
      name: Check out source repository
      uses: actions/checkout@v2
      name: Set up Python environment
      uses: actions/setup-python@v2
      name: install and run pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest

